
// SAGCO-duino CPU - Verilog Implementation
// Synthesizable for FPGA (iCE40, Tang Nano, etc.)
// Generated by SAGCO-duino Platform

module sagco_cpu (
    input wire clk,
    input wire reset,
    
    // Program memory interface
    output reg [15:0] flash_addr,
    input wire [7:0] flash_data,
    
    // RAM interface  
    output reg [10:0] ram_addr,
    output reg [7:0] ram_wdata,
    input wire [7:0] ram_rdata,
    output reg ram_we,
    
    // I/O interface
    output reg [7:0] io_addr,
    output reg [7:0] io_wdata,
    input wire [7:0] io_rdata,
    output reg io_we,
    
    // Status
    output wire halted
);

    // Registers
    reg [7:0] regs [0:31];
    reg [15:0] pc;
    reg [10:0] sp;
    reg [7:0] sreg;
    
    // State machine
    reg [3:0] state;
    localparam FETCH = 0, DECODE = 1, EXECUTE = 2, WRITEBACK = 3;
    
    // Current instruction
    reg [7:0] opcode;
    reg [7:0] arg1, arg2;
    reg [15:0] arg_word;
    
    // ALU
    reg [8:0] alu_result;
    
    // Halt flag
    reg halt_flag;
    assign halted = halt_flag;
    
    // Opcodes
    localparam OP_NOP  = 8'h00, OP_MOV  = 8'h01, OP_LDI  = 8'h02;
    localparam OP_ADD  = 8'h10, OP_SUB  = 8'h11, OP_INC  = 8'h14;
    localparam OP_DEC  = 8'h15, OP_AND  = 8'h20, OP_OR   = 8'h21;
    localparam OP_JMP  = 8'h32, OP_BREQ = 8'h33, OP_BRNE = 8'h34;
    localparam OP_OUT  = 8'h08, OP_IN   = 8'h07;
    localparam OP_HALT = 8'hFF;
    
    always @(posedge clk or posedge reset) begin
        if (reset) begin
            pc <= 0;
            sp <= 11'h7FF;
            sreg <= 0;
            state <= FETCH;
            halt_flag <= 0;
            ram_we <= 0;
            io_we <= 0;
        end else if (!halt_flag) begin
            case (state)
                FETCH: begin
                    flash_addr <= pc;
                    state <= DECODE;
                end
                
                DECODE: begin
                    opcode <= flash_data;
                    pc <= pc + 1;
                    state <= EXECUTE;
                end
                
                EXECUTE: begin
                    case (opcode)
                        OP_NOP: state <= FETCH;
                        
                        OP_HALT: begin
                            halt_flag <= 1;
                            state <= FETCH;
                        end
                        
                        OP_LDI: begin
                            // Fetch Rd
                            flash_addr <= pc;
                            pc <= pc + 1;
                            // Next cycle fetch K and store
                            state <= WRITEBACK;
                        end
                        
                        OP_ADD: begin
                            flash_addr <= pc;
                            pc <= pc + 1;
                            state <= WRITEBACK;
                        end
                        
                        OP_OUT: begin
                            flash_addr <= pc;
                            pc <= pc + 1;
                            state <= WRITEBACK;
                        end
                        
                        OP_JMP: begin
                            flash_addr <= pc;
                            pc <= pc + 1;
                            state <= WRITEBACK;
                        end
                        
                        OP_BRNE: begin
                            flash_addr <= pc;
                            pc <= pc + 1;
                            if (sreg[1] == 0) // Z flag not set
                                state <= WRITEBACK;
                            else
                                state <= FETCH;
                        end
                        
                        OP_DEC: begin
                            flash_addr <= pc;
                            pc <= pc + 1;
                            state <= WRITEBACK;
                        end
                        
                        default: state <= FETCH;
                    endcase
                end
                
                WRITEBACK: begin
                    case (opcode)
                        OP_LDI: begin
                            // flash_data has K, previous had Rd
                            regs[arg1] <= flash_data;
                            pc <= pc + 1;
                        end
                        
                        OP_OUT: begin
                            io_addr <= arg1;
                            io_wdata <= regs[flash_data];
                            io_we <= 1;
                            pc <= pc + 1;
                        end
                        
                        OP_DEC: begin
                            alu_result <= regs[flash_data] - 1;
                            regs[flash_data] <= regs[flash_data] - 1;
                            sreg[1] <= (regs[flash_data] - 1 == 0); // Z flag
                        end
                        
                        OP_JMP: begin
                            pc <= {flash_data, arg1}; // 16-bit address
                        end
                        
                        OP_BRNE: begin
                            pc <= pc + {{8{flash_data[7]}}, flash_data}; // Sign extend
                        end
                    endcase
                    
                    arg1 <= flash_data;
                    io_we <= 0;
                    state <= FETCH;
                end
            endcase
        end
    end

endmodule

// Top module with memory and I/O
module sagco_top (
    input wire clk_12mhz,
    input wire btn_reset,
    output wire [7:0] led,
    output wire uart_tx
);

    wire clk = clk_12mhz;
    wire reset = btn_reset;
    
    // Flash (program memory)
    reg [7:0] flash [0:1023];
    initial $readmemh("program.hex", flash);
    
    wire [15:0] flash_addr;
    wire [7:0] flash_data = flash[flash_addr[9:0]];
    
    // RAM
    reg [7:0] ram [0:2047];
    wire [10:0] ram_addr;
    wire [7:0] ram_wdata, ram_rdata;
    wire ram_we;
    
    assign ram_rdata = ram[ram_addr];
    always @(posedge clk)
        if (ram_we) ram[ram_addr] <= ram_wdata;
    
    // I/O
    wire [7:0] io_addr, io_wdata, io_rdata;
    wire io_we;
    
    reg [7:0] portb;
    assign led = portb;
    
    always @(posedge clk)
        if (io_we && io_addr == 8'h05) portb <= io_wdata;
    
    assign io_rdata = (io_addr == 8'h05) ? portb : 8'h00;
    
    // CPU
    sagco_cpu cpu (
        .clk(clk),
        .reset(reset),
        .flash_addr(flash_addr),
        .flash_data(flash_data),
        .ram_addr(ram_addr),
        .ram_wdata(ram_wdata),
        .ram_rdata(ram_rdata),
        .ram_we(ram_we),
        .io_addr(io_addr),
        .io_wdata(io_wdata),
        .io_rdata(io_rdata),
        .io_we(io_we),
        .halted()
    );

endmodule
