[package]
name = "sagco-core-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

# memory allocator override for instant buffer-overrun detection
[target.x86_64-unknown-linux-gnu.dependencies]
tikv-jemallocator = { version = "0.5", features = ["unprefixed_malloc_on_supported_platforms"] }

[[bin]]
name = "fuzz_lexer"
path = "fuzz_targets/fuzz_lexer.rs"
test = false
doc = false

[[bin]]
name = "fuzz_parser"
path = "fuzz_targets/fuzz_parser.rs"
test = false
doc = false

[profile.release]
debug = true       # preserve symbols for crash symbolization
opt-level = 3
overflow-checks = true
