"""
SAGCO Provenance Engine
Reads PROVENANCE.yaml and embeds the creator fingerprint into every DNA cell
as a zero-generation "soul" organelle. Also generates Obsidian-ready markdown
links so the provenance node appears at the center of the graph.
"""

from __future__ import annotations
import hashlib
import json
import time
from pathlib import Path
from typing import Any

try:
    import yaml
    _HAS_YAML = True
except ImportError:
    _HAS_YAML = False


def _load_provenance(repo_root: str | Path = ".") -> dict:
    path = Path(repo_root) / "PROVENANCE.yaml"
    if not path.exists():
        return {}
    if _HAS_YAML:
        import yaml
        return yaml.safe_load(path.read_text()) or {}
    # fallback: naive key: value reader for stdlib-only mode
    result: dict = {}
    current_key = None
    for line in path.read_text().splitlines():
        if line.startswith("#") or not line.strip():
            continue
        if not line.startswith(" ") and ":" in line:
            current_key, _, val = line.partition(":")
            current_key = current_key.strip()
            result[current_key] = val.strip()
    return result


def provenance_fingerprint(repo_root: str | Path = ".") -> dict:
    """Return the creator's fingerprint as a soul organelle dict."""
    prov = _load_provenance(repo_root)
    creator = prov.get("creator", {})
    poem = prov.get("poem", {})
    message = prov.get("message", "")
    honest = prov.get("honest_status", {})

    fingerprint_blob = json.dumps({
        "creator": creator,
        "poem_title": poem.get("title", ""),
        "message_preview": message[:128] if isinstance(message, str) else "",
    }, sort_keys=True)

    soul_digest = hashlib.sha256(fingerprint_blob.encode()).hexdigest()[:16]

    return {
        "organelle": "soul",
        "cell_type": "genesis",
        "generation": 0,
        "parent_id": None,
        "digest": soul_digest,
        "creator": creator,
        "poem": poem,
        "message": message,
        "honest_status": honest,
        "embedded_at": time.time(),
    }


def inject_soul(cell: dict, repo_root: str | Path = ".") -> dict:
    """Inject the provenance soul organelle into an existing DNA cell dict."""
    soul = provenance_fingerprint(repo_root)
    cell.setdefault("organelles", {})["soul"] = soul
    # re-weave the strand to include the soul digest
    import base64
    existing_strand = cell.get("dna_strand", "")
    combined = f"{existing_strand}:{soul['digest']}".encode()
    cell["dna_strand"] = base64.b64encode(
        hashlib.sha256(combined).digest()
    ).decode()
    return cell


def generate_obsidian_note(repo_root: str | Path = ".") -> str:
    """
    Generate a PROVENANCE.md that Obsidian can index.
    Includes [[wikilinks]] so SAGCO nodes connect to the creator fingerprint.
    """
    prov = _load_provenance(repo_root)
    creator = prov.get("creator", {})
    poem = prov.get("poem", {})
    message = prov.get("message", "")
    reach = (prov.get("honest_status") or {}).get("reach", {})
    evolution = ((prov.get("honest_status") or {}).get("reach") or
                 prov.get("honest_status", {}).get("what_the_graph_actually_shows", {}))

    name = creator.get("name", "Unknown")
    alias = creator.get("alias", "")
    poem_title = poem.get("title", "")
    poem_ref = poem.get("reference", "")

    lines = [
        f"# PROVENANCE — {name}",
        "",
        f"**alias:** `{alias}`",
        f"**node:** {creator.get('node', '')}",
        f"**contact:** {creator.get('contact', '')}",
        "",
        "## The Song",
        "",
        f"> *{poem_title}*",
        f"> {poem_ref}",
        "",
        "## The Message",
        "",
    ]

    if isinstance(message, str):
        for line in message.strip().splitlines():
            lines.append(f"> {line}" if line.strip() else ">")
    lines.append("")

    lines += [
        "## Connected Nodes",
        "",
        "[[SAGCO]] — [[sagco/README]] — [[sagco/vm]] — [[sagco/crawler]] — [[sagco/dna_cell]]",
        "",
        "[[sagco/reach]] — [[sagco-master]] — [[Obsidian Graph]]",
        "",
        "## Honest Status",
        "",
        "```yaml",
    ]

    if reach:
        for k, v in reach.items():
            if isinstance(v, dict):
                lines.append(f"  {k}:")
                for kk, vv in v.items():
                    lines.append(f"    {kk}: {vv}")
            else:
                lines.append(f"  {k}: {v}")

    lines += [
        "```",
        "",
        "---",
        "",
        "*Every folder is a question. Every graph is a map.*",
        "*Every failed compile is a lesson.*",
        "*Enough of them become a system.*",
        "",
        f"*Generated by SAGCO Provenance Engine — {time.strftime('%Y-%m-%d')}*",
    ]

    return "\n".join(lines)


if __name__ == "__main__":
    import sys
    root = sys.argv[1] if len(sys.argv) > 1 else "."

    fp = provenance_fingerprint(root)
    print("=== Soul Organelle ===")
    print(json.dumps(fp, indent=2, default=str))

    note = generate_obsidian_note(root)
    out = Path(root) / "PROVENANCE.md"
    out.write_text(note)
    print(f"\nObsidian note written → {out}")
