[package]
name    = "flame-transform"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
flametoken    = { path = "../flametoken" }
flame-parser  = { path = "../flame-parser" }
serde         = { workspace = true }
serde_json    = { workspace = true }
anyhow        = { workspace = true }
sha2          = { workspace = true }
hex           = { workspace = true }
