# Fake Malware Pod - For Detection Training Only
# âš ï¸ This contains NO actual malware - only simulates malicious behavior patterns
apiVersion: v1
kind: Pod
metadata:
  name: fake-cryptominer-001
  namespace: red-team
  labels:
    app: fake-miner
    purpose: detection-training
    team: red
    idea: "101"
  annotations:
    strategickhaos.ai/synthetic: "true"
    strategickhaos.ai/threat-type: "cryptominer"
    strategickhaos.ai/severity: "critical"
spec:
  serviceAccountName: red-team-attacker
  containers:
    - name: fake-miner
      # Using official busybox - NOT malware
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          echo "ðŸ”´ [RED TEAM] Simulating cryptominer behavior patterns..."
          echo "âš ï¸  This is a SYNTHETIC workload for detection training only"
          
          # Simulate high CPU usage (harmless busy loop)
          while true; do
            echo "Simulating mining operation $(date)"
            # Create CPU-like activity that Falco can detect
            dd if=/dev/zero of=/dev/null bs=1M count=100 2>/dev/null
            
            # Simulate suspicious network patterns (DNS queries only)
            nslookup pool.fake-mining.test 2>/dev/null || true
            
            sleep 10
          done
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
        limits:
          cpu: "200m"
          memory: "128Mi"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
  restartPolicy: Never
---
# Fake Reverse Shell Simulation
apiVersion: v1
kind: Pod
metadata:
  name: fake-reverseshell-001
  namespace: red-team
  labels:
    app: fake-shell
    purpose: detection-training
    team: red
  annotations:
    strategickhaos.ai/synthetic: "true"
    strategickhaos.ai/threat-type: "reverse-shell"
spec:
  serviceAccountName: red-team-attacker
  containers:
    - name: fake-shell
      image: busybox:1.36
      command:
        - /bin/sh
        - -c
        - |
          echo "ðŸ”´ [RED TEAM] Simulating reverse shell connection patterns..."
          echo "âš ï¸  This is a SYNTHETIC workload - no actual shell is created"
          
          # Simulate shell-like behavior that Falco can detect
          while true; do
            echo "Simulating command execution: $(date)"
            echo "Testing network connectivity to suspicious port..."
            # Attempt connection that NetworkPolicy should block
            nc -z 10.0.0.1 4444 2>/dev/null || echo "Connection blocked (expected)"
            sleep 30
          done
      resources:
        requests:
          cpu: "50m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "64Mi"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
  restartPolicy: Never
