[package]
name    = "flame-ffi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name       = "flamelang"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
serde_json  = { workspace = true }
anyhow      = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }
